services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    env_file:
      - .env.2.local
    depends_on:
      [db]
    ports:
      - "7878:7878"
  db:
    image: postgres:alpine
    env_file:
      - .env.2.local
    ports:
      - "5432:5432"
