services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    env_file:
      - .env.local
    environment:
      - DOCKERIZED=true
    depends_on:
      - db
    ports:
      - "7878:7878"
    restart: 'unless-stopped'
  db:
    image: postgres:alpine
    env_file:
      - .env.local
    ports:
      - "5432:5432"
