services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    env_file:
      - .env.2.local
    depends_on:
      [db]
    ports:
      - "7878:7878"
  db:
    image: postgres:alpine
    env_file:
      - .env.2.local
    ports:
      - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
