services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
  db:
    image: mongo
    ports:
      - "27017:27017"
