# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with pyinstaller
      run: |
        pyinstaller --icon graphics/icon.ico --noconsole SquandOfFive.py
    - name: Copy graphics
      run: |
        cp -r graphics dist/SquandOfFive/graphics
    - uses: actions/upload-artifact@v2
      with:
        name: SquadOfFive
        path: dist

